<Project>

  <PropertyGroup>
    <DotNetVersion>net8.0</DotNetVersion>
    <LangVersion>9.0</LangVersion>
    <FSharpCoreVersion>9.0.*</FSharpCoreVersion>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <NoWarn>$(NoWarn);NU1504;NU1701</NoWarn>
    <TreatWarningsAsErrors Condition="'$(Configuration)' != 'Debug'">true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <Version>3.1.1</Version>
  </PropertyGroup>

</Project>
