// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Data.GraphQL.Server.AspNet")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.GraphQL")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Facebook GraphQL query language")>]
[<assembly: AssemblyVersionAttribute("1.0.8")>]
[<assembly: AssemblyFileVersionAttribute("1.0.8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.GraphQL.Server.AspNet"
    let [<Literal>] AssemblyProduct = "FSharp.Data.GraphQL"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Facebook GraphQL query language"
    let [<Literal>] AssemblyVersion = "1.0.8"
    let [<Literal>] AssemblyFileVersion = "1.0.8"
