// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharp.Data.GraphQL.Server")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.GraphQL")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Facebook GraphQL query language")>]
[<assembly: AssemblyVersionAttribute("0.0.18")>]
[<assembly: AssemblyFileVersionAttribute("0.0.18")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Benchmarks")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.GraphQL.Server"
    let [<Literal>] AssemblyProduct = "FSharp.Data.GraphQL"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Facebook GraphQL query language"
    let [<Literal>] AssemblyVersion = "0.0.18"
    let [<Literal>] AssemblyFileVersion = "0.0.18"
    let [<Literal>] InternalsVisibleTo = "FSharp.Data.GraphQL.Benchmarks"
    let [<Literal>] InternalsVisibleTo_1 = "FSharp.Data.GraphQL.Tests"
