// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharp.Data.GraphQL.Shared")>]
[<assembly: AssemblyProductAttribute("FSharp.Data.GraphQL")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Facebook GraphQL query language")>]
[<assembly: AssemblyVersionAttribute("1.0.7")>]
[<assembly: AssemblyFileVersionAttribute("1.0.7")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Server")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Client")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Client.DesignTime")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Data.GraphQL.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Data.GraphQL.Shared"
    let [<Literal>] AssemblyProduct = "FSharp.Data.GraphQL"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Facebook GraphQL query language"
    let [<Literal>] AssemblyVersion = "1.0.7"
    let [<Literal>] AssemblyFileVersion = "1.0.7"
    let [<Literal>] InternalsVisibleTo = "FSharp.Data.GraphQL.Server"
    let [<Literal>] InternalsVisibleTo_1 = "FSharp.Data.GraphQL.Client"
    let [<Literal>] InternalsVisibleTo_2 = "FSharp.Data.GraphQL.Client.DesignTime"
    let [<Literal>] InternalsVisibleTo_3 = "FSharp.Data.GraphQL.Tests"
