name: Publish Test Results

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions: {}

jobs:
  test-results:
    if: github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.event == 'pull_request'
    name: Test Results
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: write
      pull-requests: write

    steps:
    - name: Download event file
      uses: dawidd6/action-download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        path: artifacts
        name: EventFile

    - name: Download test results
      uses: dawidd6/action-download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        path: test-results
        pattern: test-results-*

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        commit: ${{ github.event.workflow_run.head_sha }}
        event_file: artifacts/event.json
        event_name: ${{ github.event.workflow_run.event }}
        files: "test-results/**/*.trx"
